# Generated by Django 5.1 on 2024-08-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_ubicaciones/'),
        ),
    ]
