# Generated by Django 5.1 on 2024-08-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_amenaza_conservacion_habitat_delete_areaprotegida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen'),
        ),
    ]
