# Generated by Django 5.1 on 2024-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_alter_ubicacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hostales')),
                ('precio', models.CharField(max_length=200)),
            ],
        ),
    ]
