# Generated by Django 5.1 on 2024-08-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_hostales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostales',
            old_name='descripcion',
            new_name='descripcionHostal',
        ),
        migrations.RenameField(
            model_name='hostales',
            old_name='imagen',
            new_name='imagenHostal',
        ),
        migrations.RenameField(
            model_name='hostales',
            old_name='latitud',
            new_name='latitudHostal',
        ),
        migrations.RenameField(
            model_name='hostales',
            old_name='longitud',
            new_name='longitudHostal',
        ),
        migrations.RenameField(
            model_name='hostales',
            old_name='nombre',
            new_name='nombreHostal',
        ),
        migrations.RenameField(
            model_name='hostales',
            old_name='precio',
            new_name='precioHostal',
        ),
    ]
